create database mydatabase;

use mydatabase;
select * from customer_behaviour;
-- 1 total revenue generated by male vs female customers? 
select gender,sum(purchase_amount) as revenue from customer_behaviour group by gender;
-- 2 Customer used discount but still spent more than average purchase amount
select customer_id,purchase_amount from customer_behaviour where discount_applied="Yes" and purchase_amount >=(select avg(purchase_amount) from customer_behaviour);

-- 3 top 5 product with highest average review rating
select item_purchased, ROUND(avg(review_rating),2) as "Average Product Rating" from customer_behaviour group by item_purchased order by avg(review_rating)desc limit 5;
-- 4 compare avg purchase amount between standard and express shipping
select shipping_type,avg(purchase_amount)from customer_behaviour where shipping_type in('Standard','Express') group by shipping_type;
-- 5 do subscribed customers spend more?compare average and total revenue between subscribers and non-subscribers
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue 
from customer_behaviour
group by subscription_status 
order by total_revenue,avg_spend desc;
-- 6 which 5 product have highest percentage of purchase with discount applied
select item_purchased, 
round(sum(case when discount_applied ='yes' then 1 else 0 END)/count(*) * 100,2) as discount_rate
from customer_behaviour  
group by item_purchased
order by discount_rate desc
limit 5;
